name: "Yandex object storage static website"
description: "Deploy static website to Yandex Object Storage"
author: "Nikita"
inputs:
    accessKeyId:
        description: "Service account access key id"
        default: ""
        required: true
    secretAccessKey:
        description: "Service account secret access key"
        default: ""
        required: true
    bucket:
        description: "Bucket name"
        default: ""
        required: true
    path:
        description: "Path to upload folder"
        default: ""
        required: true
    clear:
        description: "Clear bucket before deploy"
        default: true
        required: false
runs:
    using: "node12"
    main: "dist/index.js"
branding:
    icon: "upload-cloud"
    color: "blue"
